kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Miuix 0.9.3 的 AAR 元数据要求 compileSdk 37；AGP 9.1.0 官方仅测试到 36.1
android.suppressUnsupportedCompileSdk=37

#Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true
